### ISSUE TITLE
Prometheus servicemonitor CRD example failing

### ISSUE THREAD

**Issue by dene14** [loft-sh/vcluster-generic-crd-sync-plugin#36]
Used provided example for prometheus. It's crashlooping like this:

```
I1115 02:10:36.814960       1 logr.go:252] plugin: Waiting for vcluster to become leader...
I1115 02:10:36.815568       1 logr.go:252] plugin: Starting syncers...
I1115 02:10:36.916286       1 logr.go:252] plugin: Start syncer ServiceMonitor-from-virtual-syncer
I1115 02:10:36.916685       1 logr.go:252] plugin: Successfully started plugin.
I1115 02:10:36.916892       1 logr.go:252] controller ServiceMonitor-from-virtual-syncer controllerGroup monitoring.coreos.com controllerKind ServiceMonitor: Starting EventSource source kind source: *unstructured.Unstructured
I1115 02:10:36.916946       1 logr.go:252] controller ServiceMonitor-from-virtual-syncer controllerGroup monitoring.coreos.com controllerKind ServiceMonitor: Starting EventSource source &{{%!s(*unstructured.Unstructured=&{map[apiVersion:monitoring.coreos.com/v1 kind:ServiceMonitor]}) %!s(*cache.informerCache=&{0xc00007eec0}) %!s(chan error=<nil>) %!s(func()=<nil>)}}
I1115 02:10:36.916960       1 logr.go:252] controller ServiceMonitor-from-virtual-syncer controllerGroup monitoring.coreos.com controllerKind ServiceMonitor: Starting Controller
I1115 02:10:37.017707       1 logr.go:252] controller ServiceMonitor-from-virtual-syncer controllerGroup monitoring.coreos.com controllerKind ServiceMonitor: Starting workers worker count 1
I1115 02:10:37.017827       1 logr.go:252] ServiceMonitor-from-virtual-syncer: insights-discovery-proxy: Create physical ServiceMonitor i56yke0idw/insights-discovery-proxy, since it is missing, but virtual object exists
I1115 02:10:37.018181       1 logr.go:252] controller ServiceMonitor-from-virtual-syncer controllerGroup monitoring.coreos.com controllerKind ServiceMonitor: serviceMonitor klog.ObjectRef{Name:"insights-discovery-proxy", Namespace:"i56yke0idw"} namespace i56yke0idw name insights-discovery-proxy: reconcileID "98226c3c-cda0-4ce1-8313-f82110b1b2a3": : Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x123a2e5]

goroutine 465 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/vcluster/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x1826e80, 0x2992910})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/loft-sh/vcluster-generic-crd-plugin/pkg/patches.replaceChildAtIndex(...)
	/go/vcluster/pkg/patches/operation.go:70
github.com/loft-sh/vcluster-generic-crd-plugin/pkg/patches.ReplaceNode(0x175db40?, 0xc000ac1540, 0xc000ac2f00)
	/go/vcluster/pkg/patches/operation.go:11 +0x65
github.com/loft-sh/vcluster-generic-crd-plugin/pkg/patches.ValidateAndTranslateName(0x1?, 0xc000ac1540, 0xc00069e320, {0x1cefb18, 0xc0006be620}, {0x0, 0x0})
	/go/vcluster/pkg/patches/patch_types.go:261 +0x145
github.com/loft-sh/vcluster-generic-crd-plugin/pkg/patches.ProcessRewrite(0x123a580?, 0xc00069e320, {0x1cefb18, 0xc0006be620})
	/go/vcluster/pkg/patches/patch_types.go:210 +0x10c
github.com/loft-sh/vcluster-generic-crd-plugin/pkg/patches.RewriteName(0xa80?, 0xc00069e320, {0x1cefb18, 0xc0006be620})
	/go/vcluster/pkg/patches/patch_types.go:181 +0x145
github.com/loft-sh/vcluster-generic-crd-plugin/pkg/patches.applyPatch(0x1a571e0?, 0xc000466080?, 0x7fbe6a3adc20?, {0x1cefb18?, 0xc0006be620?})
	/go/vcluster/pkg/patches/patch.go:78 +0x125
github.com/loft-sh/vcluster-generic-crd-plugin/pkg/patches.ApplyPatches({0x1cf9750?, 0xc000466080}, {0x0?, 0x0}, {0xc00012cf40, 0x7, 0xc0006be620?}, {0x0, 0x0, 0x0}, ...)
	/go/vcluster/pkg/patches/patch.go:41 +0x175
github.com/loft-sh/vcluster-generic-crd-plugin/pkg/syncer.(*patcher).ApplyPatches(0xc00012d280, {0x1cedbc8, 0xc000679830}, {0x1cf9750?, 0xc000466048?}, {0x0, 0x0}, {0xc00012cf40, 0x7, 0x7}, ...)
	/go/vcluster/pkg/syncer/generic.go:44 +0x105
github.com/loft-sh/vcluster-generic-crd-plugin/pkg/syncer.(*fromVirtualController).SyncDown(0xc0001aa600, 0xc000653110, {0x1cf9750?, 0xc000466048})
	/go/vcluster/pkg/syncer/from_virtual_syncer.go:84 +0x337
github.com/loft-sh/vcluster-sdk/syncer.(*syncerController).Reconcile(0xc000652fc0, {0x1cedbc8?, 0xc000679830}, {{{0xc0008ebbc0?, 0x10?}, {0xc00063bb18?, 0x40d7e7?}}})
	/go/vcluster/vendor/github.com/loft-sh/vcluster-sdk/syncer/syncer.go:96 +0x5c3
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1cedb20?, {0x1cedbc8?, 0xc000679830?}, {{{0xc0008ebbc0?, 0x1990760?}, {0xc00063bb18?, 0x4041f4?}}})
	/go/vcluster/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000c46e0, {0x1cedb20, 0xc000305ec0}, {0x189dfc0?, 0xc00007f360?})
	/go/vcluster/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000c46e0, {0x1cedb20, 0xc000305ec0})
	/go/vcluster/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/vcluster/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/vcluster/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:230 +0x325
```

**Comment by matskiv** [comment]
@dene14 Thank you for reporting the issue. Would you be able to share with us your "insights-discovery-proxy" ServiceMonitor? You can of course override any sensitive information :)

**Comment by dene14** [comment]
@matskiv sure, here it is:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"insights","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"discovery-proxy","app.kubernetes.io/version":"1.3.1-rc.1","argocd.argoproj.io/instance":"i56yke0idw","helm.sh/chart":"discovery-proxy-1.3.1-rc.1","release":"dm-prom"},"name":"insights-discovery-proxy","namespace":"i56yke0idw"},"spec":{"endpoints":[{"interval":"30s","path":"/metrics","port":"metrics"}],"namespaceSelector":{"matchNames":["i56yke0idw"]},"selector":{"matchLabels":{"app.kubernetes.io/instance":"insights","app.kubernetes.io/name":"discovery-proxy","insights.dm.com/serviceName":"insights-discovery-proxy"}},"targetLabels":["app.kubernetes.io/instance","app.kubernetes.io/name","insights.dm.com/serviceName"]}}
  creationTimestamp: "2022-11-15T02:05:01Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: insights
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: discovery-proxy
    app.kubernetes.io/version: 1.3.1-rc.1
    argocd.argoproj.io/instance: i56yke0idw
    helm.sh/chart: discovery-proxy-1.3.1-rc.1
    release: dm-prom
  name: insights-discovery-proxy
  namespace: i56yke0idw
  resourceVersion: "3185"
  uid: 25428941-7012-421c-be36-b19fc2dcb55b
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - i56yke0idw
  selector:
    matchLabels:
      app.kubernetes.io/instance: insights
      app.kubernetes.io/name: discovery-proxy
      insights.dm.com/serviceName: insights-discovery-proxy
  targetLabels:
  - app.kubernetes.io/instance
  - app.kubernetes.io/name
  - insights.dm.com/serviceName
  - ```

**Comment by matskiv** [comment]
@dene14 A new version with a fix will be available once this GH action finishes - https://github.com/loft-sh/vcluster-generic-crd-sync-plugin/actions/runs/3541987329
